import AppKit

struct ClipItem: Identifiable, Hashable {
    enum Kind: Hashable { case text(String), image(NSImage), files([URL]) }
    let id = UUID()
    let kind: Kind
    let date: Date
    let sourceApp: String?

    var preview: String {
        switch kind {
        case .text(let s): return s.trimmingCharacters(in: .whitespacesAndNewlines)
        case .image: return String(localized: "Изображение")
        case .files(let urls): return urls.map(\.lastPathComponent).joined(separator: ", ")
        }
    }

    var isLink: Bool {
        if case .text(let s) = kind, let url = URL(string: s.trimmingCharacters(in: .whitespacesAndNewlines)),
           url.scheme?.hasPrefix("http") == true { return true }
        return false
    }
}

@MainActor
final class ClipboardHistory: ObservableObject {
    @Published private(set) var items: [ClipItem] = []
    @Published var pinned: Set<UUID> = []

    private var timer: Timer?
    var onNewItem: (() -> Void)?
    private var lastChange = NSPasteboard.general.changeCount
    private var ignoreNextChange = false
    private let limit = 40

    private static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
    ]

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.6, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChange else { return }
        lastChange = pb.changeCount
        if ignoreNextChange { ignoreNextChange = false; return }
        guard Settings.shared.clipboardEnabled else { return }
        let types = Set((pb.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.concealedTypes) else { return } // password managers

        let app = NSWorkspace.shared.frontmostApplication?.localizedName
        var kind: ClipItem.Kind?
        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            kind = .files(urls)
        } else if let s = pb.string(forType: .string), !s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            kind = .text(s)
        } else if let img = NSImage(pasteboard: pb) {
            kind = .image(img)
        }
        guard let kind else { return }

        if case .text(let s) = kind {
            items.removeAll { if case .text(let o) = $0.kind { return o == s && !pinned.contains($0.id) }; return false }
        }
        items.insert(ClipItem(kind: kind, date: Date(), sourceApp: app), at: 0)
        trim()
        onNewItem?()
    }

    private func trim() {
        var unpinnedCount = 0
        items = items.filter { item in
            if pinned.contains(item.id) { return true }
            unpinnedCount += 1
            return unpinnedCount <= limit
        }
    }

    func copy(_ item: ClipItem) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch item.kind {
        case .text(let s): pb.setString(s, forType: .string)
        case .image(let img): pb.writeObjects([img])
        case .files(let urls): pb.writeObjects(urls.map { $0 as NSURL })
        }
        ignoreNextChange = true
        // Move to top
        if let i = items.firstIndex(of: item), i != 0 {
            let it = items.remove(at: i)
            items.insert(it, at: 0)
        }
    }

    func togglePin(_ item: ClipItem) {
        if pinned.contains(item.id) { pinned.remove(item.id) } else { pinned.insert(item.id) }
    }

    func remove(_ item: ClipItem) {
        items.removeAll { $0.id == item.id }
        pinned.remove(item.id)
    }

    func clear() {
        items.removeAll { !pinned.contains($0.id) }
    }
}
